### ISSUE TITLE
ClassNotFoundException in DefaultPluginFactory.create

### ISSUE THREAD

**Issue by j-barata** [hank-cp/sbp#14]
Hi,

I tried to setup a (very) simple/dummy test project in order to test your library but I'm still not able to load my application.
The source code is available here: https://github.com/j-barata/marketbasket-sbp-sample.

Actually when I try to run the application (through IntelliJ IDEA), I get the following stack and although I've read the documentation many times, I can't see what I'm doing wrong. do you have an idea ?

2020-07-26 21:34:21.133  INFO 45051 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 2700 ms
2020-07-26 21:34:21.412  INFO 45051 --- [           main] org.pf4j.DefaultPluginStatusProvider     : Enabled plugins: []
2020-07-26 21:34:21.414  INFO 45051 --- [           main] org.pf4j.DefaultPluginStatusProvider     : Disabled plugins: []
2020-07-26 21:34:21.421  INFO 45051 --- [           main] org.pf4j.DefaultPluginManager            : PF4J version 3.1.0 in 'development' mode
2020-07-26 21:34:21.436  INFO 45051 --- [           main] org.pf4j.AbstractPluginManager           : Plugin 'com.github.market.basket.sbp.sample.plugins.tomatoes@1.0.0-SNAPSHOT' resolved
2020-07-26 21:34:21.436  INFO 45051 --- [           main] org.pf4j.AbstractPluginManager           : Plugin 'com.github.market.basket.sbp.sample.plugins.potatoes@1.0.0-SNAPSHOT' resolved
2020-07-26 21:34:21.437  INFO 45051 --- [           main] org.pf4j.AbstractPluginManager           : Start plugin 'com.github.market.basket.sbp.sample.plugins.tomatoes@1.0.0-SNAPSHOT'
2020-07-26 21:35:44.484 ERROR 45051 --- [           main] org.pf4j.DefaultPluginFactory            : com.github.market.basket.sbp.sample.plugins.tomatoes.TomatoesPlugin

java.lang.ClassNotFoundException: com.github.market.basket.sbp.sample.plugins.tomatoes.TomatoesPlugin
	at org.laxture.sbp.internal.SpringBootPluginClassLoader.loadClassFromDependencies(SpringBootPluginClassLoader.java:156) ~[sbp-core-0.1.5.jar:na]
	at org.laxture.sbp.internal.SpringBootPluginClassLoader.loadClass(SpringBootPluginClassLoader.java:101) ~[sbp-core-0.1.5.jar:na]
	at org.pf4j.DefaultPluginFactory.create(DefaultPluginFactory.java:46) ~[pf4j-3.1.0.jar:3.1.0]
	at org.pf4j.PluginWrapper.getPlugin(PluginWrapper.java:79) ~[pf4j-3.1.0.jar:3.1.0]
	at org.pf4j.AbstractPluginManager.startPlugins(AbstractPluginManager.java:331) ~[pf4j-3.1.0.jar:3.1.0]
	at org.laxture.sbp.SpringBootPluginManager.init(SpringBootPluginManager.java:122) ~[sbp-core-0.1.5.jar:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:389) ~[spring-beans-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:333) ~[spring-beans-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:157) ~[spring-beans-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:416) ~[spring-beans-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1788) ~[spring-beans-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:595) ~[spring-beans-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517) ~[spring-beans-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323) ~[spring-beans-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:226) ~[spring-beans-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321) ~[spring-beans-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276) ~[spring-beans-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1304) ~[spring-beans-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1224) ~[spring-beans-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:640) ~[spring-beans-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:130) ~[spring-beans-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:399) ~[spring-beans-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1422) ~[spring-beans-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:594) ~[spring-beans-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517) ~[spring-beans-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323) ~[spring-beans-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:226) ~[spring-beans-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321) ~[spring-beans-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:893) ~[spring-beans-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:879) ~[spring-context-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:551) ~[spring-context-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:143) ~[spring-boot-2.3.1.RELEASE.jar:2.3.1.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:758) ~[spring-boot-2.3.1.RELEASE.jar:2.3.1.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:750) ~[spring-boot-2.3.1.RELEASE.jar:2.3.1.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) ~[spring-boot-2.3.1.RELEASE.jar:2.3.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) ~[spring-boot-2.3.1.RELEASE.jar:2.3.1.RELEASE]
	at com.github.market.basket.sbp.sample.application.MarketBasketApplication.main(MarketBasketApplication.java:35) ~[classes/:na]

**Comment by hank-cp** [comment]
if you want to run your project in IDEA, change `spring.sbp.runtimeMode` to `development`.

**Comment by j-barata** [comment]
Hi,
Actually it didn't worked when setting `spring.sbp.runtimeMode` to `development` (that's why I changed it).
But, if I set `spring.sbp.runtimeMode` to `development` **and**  `classes-directories` to `"target/classes"`, it works fine.

Thanks for your response.
