### ISSUE TITLE
Plugin 使用 @SpringBootApplication 出現 PluginResourceHandlerRegistrationCustomizer 無法初始化問題

### ISSUE THREAD

**Issue by Xeriou** [hank-cp/sbp#44]
我的環境是 Java8 
測試的[倉庫在這](https://github.com/Xeriou/sbptest2)
Springboot 版本為 2.7.17
Sbp 版本為 2.7.17

不管在 development mode 還是在 deployment mode 
只要 Plugin 的啟動器使用 `@SpringBootApplication` 標籤 ( [例如這樣](https://github.com/Xeriou/sbptest2/blob/34b8da5da81c4489afe2b23f4cb19e69e0d22225/plugins/PluginX/src/main/java/com/xeriou/plugins/pluginx/PluginXApplication.java#L13C21-L13C21) )
運行時就會出現

```
2023-11-14 17:52:21.153 DEBUG 24704 --- [           main] o.l.s.i.PluginListableBeanFactory        : Creating shared instance of singleton bean 'resourceHandlerRegistrationCustomizer'
2023-11-14 17:52:21.170  WARN 24704 --- [           main] s.c.a.AnnotationConfigApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'resourceHandlerRegistrationCustomizer': Unsatisfied dependency expressed through field 'webProperties'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.springframework.boot.autoconfigure.web.WebProperties' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
2023-11-14 17:52:21.176  INFO 24704 --- [           main] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2023-11-14 17:52:21.216 ERROR 24704 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   : 

***************************
APPLICATION FAILED TO START
***************************

Description:

Field webProperties in org.springframework.boot.autoconfigure.web.servlet.PluginResourceHandlerRegistrationCustomizer required a bean of type 'org.springframework.boot.autoconfigure.web.WebProperties' that could not be found.

The injection point has the following annotations:
	- @org.springframework.beans.factory.annotation.Autowired(required=true)


Action:

Consider defining a bean of type 'org.springframework.boot.autoconfigure.web.WebProperties' in your configuration.

2023-11-14 16:36:53.849 ERROR 28064 --- [           main] org.laxture.sbp.SpringBootPluginManager  : Error creating bean with name 'resourceHandlerRegistrationCustomizer': Unsatisfied dependency expressed through field 'webProperties'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.springframework.boot.autoconfigure.web.WebProperties' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'resourceHandlerRegistrationCustomizer': Unsatisfied dependency expressed through field 'webProperties'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.springframework.boot.autoconfigure.web.WebProperties' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:713) ~[spring-beans-5.3.30.jar:5.3.30]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:693) ~[spring-beans-5.3.30.jar:5.3.30]
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:119) ~[spring-beans-5.3.30.jar:5.3.30]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:408) ~[spring-beans-5.3.30.jar:5.3.30]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1431) ~[spring-beans-5.3.30.jar:5.3.30]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:619) ~[spring-beans-5.3.30.jar:5.3.30]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.30.jar:5.3.30]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.30.jar:5.3.30]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.30.jar:5.3.30]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.30.jar:5.3.30]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.30.jar:5.3.30]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:955) ~[spring-beans-5.3.30.jar:5.3.30]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:921) [spring-context-5.3.30.jar:5.3.30]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583) [spring-context-5.3.30.jar:5.3.30]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:732) ~[spring-boot-2.7.17.jar:2.7.17]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:409) ~[spring-boot-2.7.17.jar:2.7.17]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:308) ~[spring-boot-2.7.17.jar:2.7.17]
	at org.laxture.sbp.SpringBootPlugin.start(SpringBootPlugin.java:99) ~[sbp-core-2.7.17.jar:na]
	at org.laxture.sbp.SpringBootPluginManager.doStartPlugins(SpringBootPluginManager.java:149) [sbp-core-2.7.17.jar:na]
	at org.laxture.sbp.SpringBootPluginManager.startPlugins(SpringBootPluginManager.java:232) [sbp-core-2.7.17.jar:na]
	at org.laxture.sbp.internal.MainAppStartedListener.onApplicationEvent(MainAppStartedListener.java:43) [sbp-core-2.7.17.jar:na]
	at org.laxture.sbp.internal.MainAppStartedListener.onApplicationEvent(MainAppStartedListener.java:31) [sbp-core-2.7.17.jar:na]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:178) [spring-context-5.3.30.jar:5.3.30]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:171) [spring-context-5.3.30.jar:5.3.30]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:145) [spring-context-5.3.30.jar:5.3.30]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:421) [spring-context-5.3.30.jar:5.3.30]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:378) [spring-context-5.3.30.jar:5.3.30]
	at org.springframework.boot.context.event.EventPublishingRunListener.started(EventPublishingRunListener.java:108) [spring-boot-2.7.17.jar:2.7.17]
	at org.springframework.boot.SpringApplicationRunListeners.lambda$started$5(SpringApplicationRunListeners.java:78) [spring-boot-2.7.17.jar:2.7.17]
	at java.util.ArrayList.forEach(ArrayList.java:1259) ~[na:1.8.0_265]
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:120) [spring-boot-2.7.17.jar:2.7.17]
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:114) [spring-boot-2.7.17.jar:2.7.17]
	at org.springframework.boot.SpringApplicationRunListeners.started(SpringApplicationRunListeners.java:78) [spring-boot-2.7.17.jar:2.7.17]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:314) ~[spring-boot-2.7.17.jar:2.7.17]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1300) ~[spring-boot-2.7.17.jar:2.7.17]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1289) ~[spring-boot-2.7.17.jar:2.7.17]
	at com.xeriou.robotapp.RobotAppApplication.main(RobotAppApplication.java:15) ~[classes/:na]
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.springframework.boot.autoconfigure.web.WebProperties' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoMatchingBeanFound(DefaultListableBeanFactory.java:1801) ~[spring-beans-5.3.30.jar:5.3.30]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1357) ~[spring-beans-5.3.30.jar:5.3.30]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1311) ~[spring-beans-5.3.30.jar:5.3.30]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:710) ~[spring-beans-5.3.30.jar:5.3.30]
	... 36 common frames omitted
```

但是，只要將啟動改成`@ComponentScan` ([例如這樣](https://github.com/Xeriou/sbptest2/blob/34b8da5da81c4489afe2b23f4cb19e69e0d22225/plugins/PluginM/src/main/java/com/xeriou/plugins/pluginm/PluginMApplication.java#L7))  就不會出錯，且運行不會有問題。

但這樣會導致 DataSource 的 Bean 沒有辦法共用 (在 pluginx 裡)
且開發上，無法獨立運行，挺不方便的
我看大家都沒出甚麼問題，可能是我設定方式不對...

**Comment by hank-cp** [comment]
因为我这边网络的原因, maven工程build不起来, 所以目前还没有办法重现.

从你的日志里面看是因为缺少了`WebProperties`这个类, 应该是插件的配置出了问题, 导致web-mvc的AutoConfiguration没有启动.

有几个方法你可以先试试看能不能解决:
1. 给插件的Application加上`@EnableWebMvcConfiguration`
2. 给`PluginX`工程补上`application.yaml`.

**Comment by Xeriou** [comment]
老哥，感謝您撥空測試與回覆

1. 在我的倉庫中，`PluginX` 確實沒有 `application.yaml` ，但只是因為我 ignore 而已，實際上，在本地端我是有這個檔案的，但造成您檢查錯誤的思路實在很不好意思。
2. 經過測試後，確實在 Application 補上 `@EnableWebMvcConfiguration` 有效，但我在我得專案中找不到這個 annotation，因此我加了 `@EnableConfigurationProperties(WebProperties.class)` 後就能正常跑了...

老實說，我目前不太清楚為甚麼會有這種原因，理論上如果 properties 中有 spring.web 的 tag，應該是會自動啟用這些設定檔
但我不管在 外部的 config 資料夾中新增，或是在 `PluginX` 的 resource 新增，似乎都沒有讀取到；最終，還是直接在 Application 中 Enable 這個方法才正確(可能也不是最正確的選擇)。我會繼續測試下去的!

**Comment by hank-cp** [comment]
经过测试, 可以确认这是一个bug.

在`SpringBootstrap`中, 引入`WebProperties`的`WebMvcAutoConfiguration`被禁用了. 这边demo工程能启动的原因是`WebProperties`被其它AutoConfiguration引入了.

可以先通过`@EnableConfigurationProperties(WebProperties.class)`绕开这个问题.

感谢反馈!
