### ISSUE TITLE
Got ClassNotFoundException when load Plugin

### ISSUE THREAD

**Issue by luanact247** [hank-cp/sbp#54]
Hi Hank,

I was using your project sbp to extend function by plugin.
But I got ClassNotFoundException when Start plugin.
Could you help me?

Detail log here: 
2024-05-21 14:43:16.918  INFO 35822 --- [           main] c.s.v.pfw.PluginFrameworkApplication     : Starting PluginFrameworkApplication v0.0.1 using Java 1.8.0_333 on MacBook-Luan.local with PID 35822 (/Users/edward/app/bitel/sbp/code/test/plugin-framework-0.0.1.jar started by edward in /Users/edward/app/bitel/sbp/code/test)
2024-05-21 14:43:16.924  INFO 35822 --- [           main] c.s.v.pfw.PluginFrameworkApplication     : No active profile set, falling back to default profiles: default
2024-05-21 14:43:18.885  INFO 35822 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8080 (http)
2024-05-21 14:43:18.900  INFO 35822 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2024-05-21 14:43:18.900  INFO 35822 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.55]
2024-05-21 14:43:18.979  INFO 35822 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2024-05-21 14:43:18.979  INFO 35822 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 1937 ms
2024-05-21 14:43:19.910  INFO 35822 --- [           main] org.pf4j.DefaultPluginStatusProvider     : Enabled plugins: []
2024-05-21 14:43:19.912  INFO 35822 --- [           main] org.pf4j.DefaultPluginStatusProvider     : Disabled plugins: []
2024-05-21 14:43:19.916  INFO 35822 --- [           main] org.pf4j.DefaultPluginManager            : PF4J version 3.8.0 in 'deployment' mode
2024-05-21 14:43:19.952  INFO 35822 --- [           main] org.pf4j.AbstractPluginManager           : Plugin 'plugin-ftth@0.0.1' resolved
2024-05-21 14:43:20.115  INFO 35822 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8080 (http) with context path ''
2024-05-21 14:43:20.140  INFO 35822 --- [           main] c.s.v.pfw.PluginFrameworkApplication     : Started PluginFrameworkApplication in 3.912 seconds (JVM running for 4.732)
2024-05-21 14:43:20.149 ERROR 35822 --- [           main] org.pf4j.DefaultPluginFactory            : com.pfw.commission.pluginftth.FtthPlugin

java.lang.ClassNotFoundException: com.pfw.commission.pluginftth.FtthPlugin
	at org.pf4j.PluginClassLoader.loadClass(PluginClassLoader.java:144) ~[pf4j-3.8.0.jar!/:3.8.0]
	at org.laxture.sbp.internal.SpringBootPluginClassLoader.loadClass(SpringBootPluginClassLoader.java:102) ~[sbp-core-2.7.17.jar!/:na]
	at org.pf4j.DefaultPluginFactory.create(DefaultPluginFactory.java:46) ~[pf4j-3.8.0.jar!/:3.8.0]
	at org.pf4j.PluginWrapper.getPlugin(PluginWrapper.java:81) [pf4j-3.8.0.jar!/:3.8.0]
	at org.laxture.sbp.SpringBootPluginManager.doStartPlugins(SpringBootPluginManager.java:145) [sbp-core-2.7.17.jar!/:na]
	at org.laxture.sbp.SpringBootPluginManager.startPlugins(SpringBootPluginManager.java:232) [sbp-core-2.7.17.jar!/:na]
	at org.laxture.sbp.internal.MainAppStartedListener.onApplicationEvent(MainAppStartedListener.java:43) [sbp-core-2.7.17.jar!/:na]
	at org.laxture.sbp.internal.MainAppStartedListener.onApplicationEvent(MainAppStartedListener.java:31) [sbp-core-2.7.17.jar!/:na]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176) [spring-context-5.3.13.jar!/:5.3.13]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169) [spring-context-5.3.13.jar!/:5.3.13]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143) [spring-context-5.3.13.jar!/:5.3.13]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:421) [spring-context-5.3.13.jar!/:5.3.13]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:378) [spring-context-5.3.13.jar!/:5.3.13]
	at org.springframework.boot.context.event.EventPublishingRunListener.started(EventPublishingRunListener.java:105) [spring-boot-2.4.13.jar!/:2.4.13]
	at org.springframework.boot.SpringApplicationRunListeners.lambda$started$5(SpringApplicationRunListeners.java:75) [spring-boot-2.4.13.jar!/:2.4.13]
	at java.util.ArrayList.forEach(ArrayList.java:1259) ~[na:1.8.0_333]
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:117) [spring-boot-2.4.13.jar!/:2.4.13]
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:111) [spring-boot-2.4.13.jar!/:2.4.13]
	at org.springframework.boot.SpringApplicationRunListeners.started(SpringApplicationRunListeners.java:75) [spring-boot-2.4.13.jar!/:2.4.13]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:345) ~[spring-boot-2.4.13.jar!/:2.4.13]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1329) ~[spring-boot-2.4.13.jar!/:2.4.13]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1318) ~[spring-boot-2.4.13.jar!/:2.4.13]
	at com.spower.viettel.pfw.PluginFrameworkApplication.main(PluginFrameworkApplication.java:10) ~[classes!/:0.0.1]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_333]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_333]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_333]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_333]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[plugin-framework-0.0.1.jar:0.0.1]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) ~[plugin-framework-0.0.1.jar:0.0.1]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[plugin-framework-0.0.1.jar:0.0.1]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) ~[plugin-framework-0.0.1.jar:0.0.1]

**Comment by hank-cp** [comment]
Couldn't see anything wrong form your log. Please make a reproduciable repository for your issue.

**Comment by hank-cp** [comment]
This issue was closed because it has been inactive.
